### ISSUE TITLE
 regression bug in 2.18.0 CsvMapper().readerFor(Map.class).with(schema).readValues(csvReader))->NoSuchMethodError: 'void com.fasterxml.jackson.core.base.ParserMinimalBase.<init>(int, com.fasterxml.jackson.core.StreamReadConstraints)

### ISSUE THREAD

**Issue by bodote** [FasterXML/jackson-dataformats-text#500]
This works in 2.17.2 but not in 2.18.0.

```java
public <Y> List<Y> readCSVToListe(BufferedReader csvReader, BiConsumer<Map<String, String>, List<Y>> lineAdder)
            throws IOException {
        CsvMapper csvMapper = new CsvMapper();
        CsvSchema schema = CsvSchema.emptySchema().withHeader().withColumnSeparator(';');
        try (MappingIterator<Map<String, String>> iterator =
                csvMapper.readerFor(Map.class).with(schema).readValues(csvReader)) {
            List<Y> theList = new ArrayList<>();
            while (iterator.hasNext()) {
                Map<String, String> line = iterator.next();
                lineAdder.accept(line, theList);
            }
            return theList;
        }
    }
```

in  2.18.0 the call to `readValues(csvReader)` results in error 

```
, StackTrace=jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.base.ParserMinimalBase.<init>(int, com.fasterxml.jackson.core.StreamReadConstraints)
...
Caused by: java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.base.ParserMinimalBase.<init>(int, com.fasterxml.jackson.core.StreamReadConstraints)'
	at com.fasterxml.jackson.dataformat.csv.CsvParser.<init>(CsvParser.java:433)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory._createParser(CsvFactory.java:404)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory.createParser(CsvFactory.java:306)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory.createParser(CsvFactory.java:14)
	at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1136)
	at com.fasterxml.jackson.databind.ObjectReader.readValues(ObjectReader.java:1946)
	at de.bas.adapters.driving.repositories.CSVFromResourceReader.readCSVToListe(CSVFromResourceReader.java:52)

**Comment by cowtowncoder** [comment]
You have version mismatch wrt `jackson-core`: make sure it's also 2.18.0, not something older.
