### ISSUE TITLE
YAMLParser >2.17.2 is not compatible with jackson-core?

### ISSUE THREAD

**Issue by antonavery-oviva** [FasterXML/jackson-dataformats-text#563]
YAMLParser uses `_updateToken` method that is supposed to come from ParserBase from jackson-core, but there is no such method in YAMLParser or ParserBase. It is in ParserMinimalBase, but somehow I still get:
```
java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.JsonToken com.fasterxml.jackson.dataformat.yaml.YAMLParser._updateToken(com.fasterxml.jackson.core.JsonToken)'
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:532)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4934)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3313)
```

This works in `2.17.2` though, but not in higher versions.

**Comment by cowtowncoder** [comment]
As long as minor versions match (which they have to -- `jackson-core`, `jackson-databind`, `jackson-dataformat-yaml`) things should work. Make sure they do tho, I am 99% sure they don't.

**Comment by cowtowncoder** [comment]
Almost certainly version mismatch, closing.
