### ISSUE TITLE
Updating to 2.18.0 throws java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.base.ParserMinimalBase.<init>(int, com.fasterxml.jackson.core.StreamReadConstraints)' when using the CsvParser

### ISSUE THREAD

**Issue by pierre-isb** [FasterXML/jackson-dataformats-text#503]
## Description

Trying to update `com.fasterxml.jackson.dataformat:jackson-dataformat-csv` to version 2.18.0, our automated tests discovered a bug when using the `CsvParser`, which throws a `NoSuchMethodError` while trying to call a method from `com.fasterxml.jackson.core`.

## Version information
2.18.0

## Reproduction

Update to 2.18.0 with a Csv loader as such :

```java
import com.fasterxml.jackson.databind.MappingIterator;
import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;

@AllArgsConstructor
public class CsvDataLoader {

  private final CsvSchema bootstrapSchema;
  private final CsvMapper mapper;

  public <T> List<T> loadObjectList(Class<T> type, String fileName) {
    try {
      InputStream inputStream = new ClassPathResource(fileName).getInputStream();
      try (MappingIterator<T> readValues =
          mapper.readerFor(type).with(bootstrapSchema).readValues(inputStream)) {
        return readValues.readAll();
      }
    } catch (IOException e) {
      throw new MyException(e);
    }
  }
}
```

throws :

```bash
Exception java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.base.ParserMinimalBase.<init>(int, com.fasterxml.jackson.core.StreamReadConstraints)' [in thread "Test worker"]
            at com.fasterxml.jackson.dataformat.csv.CsvParser.<init>(CsvParser.java:433)
            at com.fasterxml.jackson.dataformat.csv.impl.CsvParserBootstrapper.constructParser(CsvParserBootstrapper.java:162)
            at com.fasterxml.jackson.dataformat.csv.CsvFactory._createParser(CsvFactory.java:390)
            at com.fasterxml.jackson.dataformat.csv.CsvFactory.createParser(CsvFactory.java:300)
            at com.fasterxml.jackson.dataformat.csv.CsvFactory.createParser(CsvFactory.java:14)
            at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1123)
            at com.fasterxml.jackson.databind.ObjectReader.readValues(ObjectReader.java:1935)
            at com.my.lib.CsvDataLoader.loadObjectList(CsvDataLoader.java:24)
```

**Comment by cowtowncoder** [comment]
You have an old version of `jackson-core`: to work with a dataformat module version 2.18.0, both `jackson-databind` and `jackson-core` must be at least 2.18.x.
In general minor versions of all components should match, but specifically components module depends on  (like CSV depending on databind, core) must be at least same minor version.

So please check your dependencies; specifically `jackson-core`.

**Comment by cowtowncoder** [comment]
@pierre-isb Glad you were able to fix the issue & thanks for the update!

One thing that can be help ensure consistent versions of components is using `jackson-bom` (import in Maven): https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-bom

When imported like so, you can then omit `<version>` tags from actual dependencies:

```
    <dependencyManagement>
      <dependencies>
        <dependency>
          <groupId>com.fasterxml.jackson</groupId>
          <artifactId>jackson-bom</artifactId>
          <type>pom</type>
          <version>2.18.0</version>
          <scope>import</scope>
        </dependency>
      </dependencies>
    </dependencyManagement>   
```
