### ISSUE TITLE
Failed to generate CSV file  after upgrading from 2.12.4 to 2.17.1

### ISSUE THREAD

**Issue by maliksajidhussain** [FasterXML/jackson-dataformats-text#478]
I am using jackson-dataformat-csv to generate CSV  file.. previously I was using 2.12.4 version and this code to generate CSV.
`FileWriter outputCpFile = new FileWriter(csvCpFile, true);
PrintWriter cpWriter = new PrintWriter(outputCpFile);
CsvMapper csvMapper = new CsvMapper();
CsvSchema csvSchema = csvMapper.schemaFor(CpTransactionLogs.class).withHeader();
csvMapper.enable(CsvGenerator.Feature.ALWAYS_QUOTE_EMPTY_STRINGS);
String csvString = csvMapper.writer(csvSchema).writeValueAsString(transLogs);
cpWriter.write(csvString);`

After upgrading to 2.17.1 I'm getting following exception:
`(java.lang.NoSuchMethodError) java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.base.GeneratorBase.<init>(int, com.fasterxml.jackson.core.ObjectCodec, com.fasterxml.jackson.core.io.IOContext)'`

Any workaround how to fix this issue.

Thanks in advance

**Comment by maliksajidhussain** [comment]
`java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.base.GeneratorBase.<init>(int, com.fasterxml.jackson.core.ObjectCodec, com.fasterxml.jackson.core.io.IOContext)'
        at com.fasterxml.jackson.dataformat.csv.CsvGenerator.<init>(CsvGenerator.java:274) ~[khatim-diagnostic.jar:1.0]
        at com.fasterxml.jackson.dataformat.csv.CsvFactory._createGenerator(CsvFactory.java:442) ~[khatim-diagnostic.jar:1.0]
        at com.fasterxml.jackson.dataformat.csv.CsvFactory._createGenerator(CsvFactory.java:417) ~[khatim-diagnostic.jar:1.0]
        at com.fasterxml.jackson.dataformat.csv.CsvFactory.createGenerator(CsvFactory.java:360) ~[khatim-diagnostic.jar:1.0]
        at com.fasterxml.jackson.dataformat.csv.CsvFactory.createGenerator(CsvFactory.java:14) ~[khatim-diagnostic.jar:1.0]
        at com.fasterxml.jackson.databind.ObjectWriter.createGenerator(ObjectWriter.java:751) ~[khatim-diagnostic.jar:1.0]
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1114) ~[khatim-diagnostic.jar:1.0]`

**Comment by yawkat** [comment]
You are using an outdated version of jackson-core.

**Comment by maliksajidhussain** [comment]
@yawkat Thanks for the help. The jackson-databind 2.17.1 by default adding older version of core and annotation dependencies. wondering previously writing array of object working but now its throw error stream close. Here is the code to add multiple rows
`FileWriter outputCpFile = new FileWriter(csvCpFile, true);
CsvMapper csvMapper = new CsvMapper();
CsvSchema csvSchema = csvMapper.schemaFor(testing.class).withHeader();
csvMapper.enable(CsvGenerator.Feature.ALWAYS_QUOTE_EMPTY_STRINGS);
csvMapper.writerFor(testing.class).with(csvSchema).writeValue(outputCpFile, obj);`
